#!/usr/bin/env python

from igLibraryQC import main
# ## Main Code
# ## TO RUN: caffeinate python analyzeNGSLibrary.py -f1 <file1> -f2 <file2> -o <output_dir> -merged yes -fmt fastq -bitscore 100
if (__name__ == '__main__'):
    main()
