#!/usr/bin/env python
'''
    Short description: Quality Control Analysis of Immunoglobulin Repertoire NGS (Paired-End MiSeq)    
    Author: Monther Alhamdoosh    
    Python Version: 2.7
    Changes log: check git commits. 
''' 



from abseqQC import main
# ## Main Code
# ## TO RUN: caffeinate python analyzeNGSLibrary.py -f1 <file1> -f2 <file2> -o <output_dir> -merged yes -fmt fastq -bitscore 100
if (__name__ == '__main__'):
    main()
