#!/usr/bin/env python
'''
    Short description: Quality Control Analysis of Immunoglobulin Repertoire NGS (Paired-End MiSeq)    
    Author: Monther Alhamdoosh    
    Python Version: 2.7
    Changes log: check git commits. 
''' 
from abseqPy.abseqQC import main

if __name__ == '__main__':
    main()
